name: Test live checkout for clients
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  nightly-test:
    name: ${{ matrix.client[0] }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/e2e
    strategy:
      matrix:
        client:
          [
              ['cantastic', 'https://cantastic.nl/' ]
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: google-chrome --version
      - name: Build
        run: yarn
      - name: Test checkout
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: cd packages/e2e && TESTCASE=${{ matrix.client[0] }} yarn nightwatch:checkout
      - name: Check for 404's on ${{ matrix.client[1] }}
        run: yarn linkinator ${{ matrix.client[1] }} --skip '^(?!${{ matrix.client[1] }})' --recurse --verbosity 'error'
